### PR TITLE
First draft of baseball data viz (pitching)

### PR DESCRIPTION
**Pull request by mlamoureux**
Ready for review. The data viz of the week draft, on data about baseball pitching. (Fast balls, curve balls, etc. Balls and strikes.) Please leave comments, let Michael know if more or less is needed.

### CODE REVIEW

**Comment by mlamoureux** [comment]
Revisions made, as per Tina and David's comment. I think it is ready for merging to main.

**Comment by byrcyb** [comment]
@mlamoureux  Can you choose and generate a couple of html image files of the visualizations that we can use in a blog post and add to the repo?

**Comment by byrcyb** [comment]
@mlamoureux I think the `LesterPitches.html`and `DarvishPitches.html` are identical. I’m not sure if it’s a problem with the original graph that I didn’t notice or maybe when you were writing it out there was a typo? Also for the `DarvishPitches.html` the graph title has the name Jon Lester instead of Yu Darvish.

**Review by byrcyb — APPROVED** [review]
A great deep dive on the topic of baseball pitching! I really like all the visuals and the difference in pitching styles between Darvish and Lester are really apparent.

**Pull request merged**
