### PR TITLE
add age of empires dvofw

### PR DESCRIPTION
**Pull request by lgfunderburk**
@BryceHaley please review

### CODE REVIEW

**Review by BryceHaley — DISMISSED** [review]

**Comment by BryceHaley** [comment]
Looks good. I think we should wait for @TinaL5 to review the template as I found the communications bit in the notebook a bit weak (but thats the template). 

I really hope kids know what age of empires is still!

**Comment by TinaL5** [comment]
@BryceHaley If you have any suggestions for the template, please let me know. I am working on it today.

I am just looking at the game description of Age of Empires in the notebook now, and it sound like an interesting game.

**Comment by TinaL5** [comment]
no_wonder :)

Question: How different are the costs associated with each of the different structures in Age of Empires II?
I am guessing that the costs are time units? I'm not familiar with the game and was wondering how costs were articulated in the interpretation.

**Review by TinaL5 — CHANGES_REQUESTED** [review]
@lgfunderburk 
I think that we can extend the grade level to grade 7. The box plot is not applicable, but the bar graph and representation of an outlier are applicable.

**Comment by BryceHaley** [comment]
Can we merge this before EOD, Friday and update this tracker? https://docs.google.com/spreadsheets/d/1x0OA3cHqRarjKofLXlka-A5RgvJfZQ442PrzTWI8tWU/edit#gid=0

@lgfunderburk , if you're busy and would like me to make the requested edits, let me know.

**Comment by lgfunderburk** [comment]
Need to add minor changes. Will add those before EOD today

**Comment by lgfunderburk** [comment]
Added changes. Please review. Once ready, feel free to merge PR.

**Review by BryceHaley — APPROVED** [review]

**Review by TinaL5 — APPROVED** [review]

**Pull request merged**
