### PR TITLE
Twitch.png ad removal

### PR DESCRIPTION
**Pull request by TinaL5**

### CODE REVIEW

**Comment by byrcyb** [comment]
@mlamoureux I made a few changes to use plotly express and also to sort the "Watch" and "Peak viewers" columns before they get plotted so that we are getting the top 10. Have a look and let me know what you think.

**Comment by mlamoureux** [comment]
Looks good. I like the removal of ads (wish I had thought of that!) and simplifying the plotting libraries. Appreciate the grammar and coding fixes.

**Review by mlamoureux — APPROVED** [review]
Looks good. I like the removal of ads (wish I had thought of that!) and simplifying the plotting libraries. Appreciate the grammar and coding fixes.

**Comment by mlamoureux** [comment]
PR approved and merged.

**Pull request merged**
