### PR TITLE
Sunrise Sunset notebook

### PR DESCRIPTION
**Pull request by mrbubbleman**
Created a data viz looking at sunset, sunrise, and day lengths given a particular longitude and latitude.

-  Imports data using Sunrise and Sunset API (credit given)
-  Ability to switch timezones in order to obtain correct local times
-  Added starting date and ending date functionality so users can visualize differences in sunset, sunrise, and day lengths
- Added correct markdown to notebooks
- Finished plots for sunrise, sunset, and day lengths

Things that can be added
- Times on the y_axis don't plot correctly for certain ranges of dates (1yr+), potential fix can be added

### CODE REVIEW

**Comment by misterhay** [comment]
This is looking good. A few notes, though:

* The library `tzfpy` isn't installed on the Hub. Can we use [things from the standard library](https://www.tutorialspoint.com/How-to-convert-date-and-time-with-different-timezones-in-Python)?
* Remember to clear all cell outputs before pushing commits.

**Comment by mlamoureux** [comment]
The moldule "zoneinfo" is in the standard installation. Try using that instead of 
"tzfpy" as mentioned above. https://docs.python.org/3/library/zoneinfo.html

**Comment by mrbubbleman** [comment]
- Simplified the timezone section to set it in MST from UTC from the beginning. 
-  Gave students the option to change their timezone from searching up from a site mainly because there are chances students misinput incorrect timezones mainly due to syntax.

**Comment by misterhay** [comment]
Looking good. For the visualizations in `sunset-sunrise.ipynb` can you put all three on one figure using [subplots](https://plotly.com/python/subplots)?

And I'm assuming that you we longer need the `day-length.ipynb` file...

**Review by misterhay — APPROVED** [review]
Looks great

**Pull request merged**
