### PR TITLE
Climate change temperature

### PR DESCRIPTION
**Pull request by mlamoureux**
Improved the notebook with annual temps in trend. Added html visualizations. Should be ready to go.

### CODE REVIEW

**Review by TinaL5 — CHANGES_REQUESTED** [review]
Accept previous edits, label Edmonton avg_temperature plot, customization values unclear, update city_view.html

**Review by BryceHaley — APPROVED** [review]
Looks good

**Review by TinaL5 — CHANGES_REQUESTED** [review]
customization part 3: LinAlgError: SVD did not converge in Linear Least Squares
@mlamoureux temp_list choice 3 doesn't work with any of the cities; the other choices now work

**Comment by BryceHaley** [comment]
@TinaL5 where you running it locally on on the hub?

I cannot recreate this bug in either enviroment.

**Comment by BryceHaley** [comment]
After you guys merge this, I can add try catch blocks to the code from another branch. So it will still output something meaningful when errors.

**Review by TinaL5 — APPROVED** [review]

**Pull request merged**
