### PR TITLE
Line graph lights

### PR DESCRIPTION
**Pull request by BryceHaley**
Add final DVoTW for the year 2020.

### CODE REVIEW

**Comment by lgfunderburk** [comment]
Change 

```
print(df.columns)
print(df.head())
```

to

```
print(df.columns)
display(df.head())
```

**Comment by lgfunderburk** [comment]
First plot is confusing, too many lines at once, also value for Canada is lower than province values. 

Suggestion: plot subset of the data for all areas except for Canada.

Suggestion 2, plot bar chart per year and add instructions on how to change the code to see bar chart (or line chart) for each of the four years. 

`df_small = df_small[df_small['area']!='Canada']

px.bar(df_small,x='area',
       y=2011,
       title="Percentage of households using holiday LEDs").update_xaxes(categoryorder='total descending')`

**Review by lgfunderburk — CHANGES_REQUESTED** [review]
Opportunities to improve output and plot readability. See comments for details.

**Comment by BryceHaley** [comment]
As per feedback:
* print statement replaced with delay. This does lead the output window of the cell to have a lateral scroll bar; and
* plot modified to not include national percentages. Only provincial. The legend name is updated also.

Re requesting feedback from @lgfunderburk .

**Pull request merged**
