### PR TITLE
Privacy policies readability

### PR DESCRIPTION
**Pull request by raniamahdi**
Notebook for privacy policy data visualization is added

### CODE REVIEW

**Comment by AyushChaudhari2001** [comment]
Couple of comments

- I'm not sure if the search_for_site function is working. I'm only able to get "No website" as the output. Even for the default input of "twitter" I still only get "No website".
- Maybe add another explanation of the grade score as I was a little confused on what a score of 21 would mean. It gives the example of a grade score of 5 to be equal to a fifth grader. So would that mean somebody a grade score of 21 would be equal to somebody in grade 21 being able to read it.
- Add the units for reading time (i.e. seconds) to remove ambiguity
- In the data frame we use "grade_score" but in the bar chart visualization we use grade trace. I think we should stay consistent with the naming (or explicitly state that they're interchangeable)
- We should also add an analysis of what the correlations mean. This will help the user draw conclusions on how each variable is related to one another.
- There's a few words bolded in the "Communicate" section which doesn't really make sense to bold

**Comment by raniamahdi** [comment]
Changes have been made to address feedback comments

**Comment by raniamahdi** [comment]
all "grade trace" in mark down has been changed to "grade level" for consistency between the graphs and explanations

**Review by misterhay — APPROVED** [review]
Looks good

**Pull request merged**
