### PR TITLE
Merge NHANES BP examination notebook into main

### PR DESCRIPTION
**Pull request by jswan5**
Incorporated final changes requested from @byrcyb, ready to merge

### CODE REVIEW

**Comment by meghbali** [comment]
The notebook looks good to me and is ready for merging. A general comment though: Is it a good idea to ask students to compare their heights to the published data (and probably with each other)? Just something to double check with the education specialists.

**Review by meghbali — APPROVED** [review]
The notebook looks good to me and is ready for merging. A general comment though: Is it a good idea to ask students to compare their heights to the published data (and probably with each other)? Just something to double check with the education specialists.

**Comment by byrcyb** [comment]
Next steps - @jswan5 is moving data files and visualization files to the data-files repo to limit repo size, and updating code to use this remote data source.

**Comment by jswan5** [comment]
I've removed the data and viz files after changing the code in the notebook to use the new file locations, and verifying that it runs without issue. Outputs cleared as well.

@meghbali the education specialists didn't have any concerns with it, but they had earlier expressed concern about doing similar measurements with weight and circumference measurements, so that part was dropped.

**Pull request merged**
