### PR TITLE
Rock paper scissors initial version

### PR DESCRIPTION
**Pull request by misterhay**
Here is a working notebook, edits and comments welcomed.

### CODE REVIEW

**Comment by BryceHaley** [comment]
I suggest exporting the bar chart as html + adding some more text about the visual and some of the helper instructions from the first few cells in the template. @TinaL5, thoughts ?

**Comment by TinaL5** [comment]
Suggestions
- Start with a question: Have you ever wondered how...? has been to go to in the past DVotW.
- Names: What happened to Alice and Bob? Should the names be neutral?
- Replace choices with decisions to clearly align with decision making
- Explain difference between playing in real-life and simulation. In real-life, if the game is played quickly, near randomness may be achieved because the capacity to strategize quickly becomes difficult -- there is less time to think. In this simulation decisions are defined, so outcomes are also defined.
- Keep win/lose table in html version?
- Would it be worthwhile to change to 100 rounds to be able to convert to percentages more easily? The results table would have to be limitted though.
- Not sure if this is possible, but it would be neat to be able to change strategies for the losing player during a tournament to explore different outcomes.

**Comment by misterhay** [comment]
> * Names: What happened to Alice and Bob? Should the names be neutral?

I was trying to be clever with the names: `Steven` evenly chooses the three options, `Edward` has scissor hands, poor predictable `Bart` always picks rock, and `Freddie` Mercury follows the "we will rock you" pattern.

You're right, though, this needs to be rewritten to follow the template and pattern of the previous data visualizations. And I'm not sure how we could create a web-based (html export) version that would allow for different simulations, since it wouldn't have access to a Python kernel.

**Review by TinaL5 — COMMENTED** [review]
I think that the blogs still contain a link to the notebooks.

Question 
Gather - Would data be gathered from the tournament? 
Organize - the table
Explore - Examine the data to look for evidence to answer our question. (table + graph)
Interpret - Explain how the evidence answers our question. evidence/output  
Communicate - Reflect on the interpretation.

Has a decision been made to only have this notebook as an interesting problem?

**Comment by mlamoureux** [comment]
Suggestion: remind the user that they can "scroll through" the animation using the scroll bar.
I was hitting the "run" button and getting annoyed at how slow the animation was, when I had 500+ trials. 
Then I eventually realized I could just scroll through the results. A "reminder" would have helped me.

**Comment by mlamoureux** [comment]
I think it is funny that if one guy chooses evenly (like Even Steven), it doesn't matter who the other play is, the results are still roughly fair. I didn't realize that before. In real life, if one guy like "Bart" always choose "Rock" the other play knows how to change their choices (to paper) in order to win. Now I want to write a simulation that allows for "feedback" so the players might change their strategy of choices given what the other player is doing. Maybe some of our "audience" will be similarly motivated.

**Comment by mlamoureux** [comment]
Re the names (not Alice and Bob, but Steven, Bart, Edward, Freddie) -- seems pretty white and male, and not everyone will necessarily get the joke. Instead of "Steven" you could use " Adil " which is a pretty common mid-Eastern name meaning "fair and honest." The name "Pedra" means "rock" as does Pierre (male) or Pierrette (female). Or Dwayne Johnson :-). As I write this, it occurs to me that we could have a lot of fun with the names cross-culturally and be a bit more inclusive.  It might be hard to do better than "Edward Scissorhands" though...

**Comment by BryceHaley** [comment]
> > * Names: What happened to Alice and Bob? Should the names be neutral?
> 
> I was trying to be clever with the names: `Steven` evenly chooses the three options, `Edward` has scissor hands, poor predictable `Bart` always picks rock, and `Freddie` Mercury follows the "we will rock you" pattern.
> 
> You're right, though, this needs to be rewritten to follow the template and pattern of the previous data visualizations. And I'm not sure how we could create a web-based (html export) version that would allow for different simulations, since it wouldn't have access to a Python kernel.

I tested creating an html plot and pushed the example to this branch. It works just fine with the usual: 

```import plotly.io as pio
pio.write_html(fig,"name.html", auto_open=True, include_plotlyjs=True)```

**Comment by TinaL5** [comment]
@mlamoureux I am definitely in support of a technological feedback loop.

@BryceHaley I'm glad you got the html version working.

Any thoughts on whether the output of the simulation can be used as data in the analysis process? This approach would reflect real-world application.

**Comment by misterhay** [comment]
I don't have a strong preference for whether this should be a Data Viz of the Week or an [Interesting Problem](https://github.com/callysto/interesting-problems/blob/main/notebooks/rock-paper-scissors.ipynb).

**Comment by BryceHaley** [comment]
Can we merge this by EOD Friday unless there is an alternative made?

After it is merged, please update this tracker for comms: https://docs.google.com/spreadsheets/d/1x0OA3cHqRarjKofLXlka-A5RgvJfZQ442PrzTWI8tWU/edit#gid=0

**Comment by byrcyb** [comment]
This notebook is really fun. I like the attention that it would get as a Data Viz of the Week but it might work better as an Interesting Problem to start with and maybe in the future expanding it out as a stats probability activity notebook. I'll close the PR and look at potentially a different dataset/notebook for Data Viz of the Week.

**Pull request closed without merging**
